#!/bin/bash -e
ZEEK=${1}
ZEEK_VER=${2}
BUILD_TYPE=${3-Release}

URL=https://download.zeek.org/${ZEEK}-${ZEEK_VER}.tar.gz

mkdir -p /opt/src/
cd /opt/src/
if [ ! -e "${ZEEK}-${ZEEK_VER}.tar.gz" ] ; then 
    wget -c "${URL}"
fi
if [ ! -d "${ZEEK}-${ZEEK_VER}" ]; then
    tar xvzf "${ZEEK}-${ZEEK_VER}.tar.gz"
    rm -f "${ZEEK}-${ZEEK_VER}.tar.gz"
fi
cd "${ZEEK}-${ZEEK_VER}"
./configure --prefix="/usr/local/${ZEEK}-${ZEEK_VER}" --build-type="${BUILD_TYPE}"
make -j "$(nproc)" install

# Clean
rm -rf build
rm -rf testing
