#!/bin/bash -e
ZEEK=${1}
VER=${2}
BUILD_TYPE=${3-Release}

URL=https://download.zeek.org/${ZEEK}-${VER}.tar.gz

cd /usr/src/
if [ ! -e "${ZEEK}-${VER}.tar.gz" ] ; then 
    wget -c "${URL}"
fi
if [ ! -d "${ZEEK}-${VER}" ]; then
    tar xvzf "${ZEEK}-${VER}.tar.gz"
    rm -f "${ZEEK}-${VER}.tar.gz"
fi
cd "${ZEEK}-${VER}"
./configure --prefix="/usr/local/${ZEEK}-${VER}" --build-type="${BUILD_TYPE}"
make -j "$(nproc)" install
rm -rf build
rm -rf testing
file /usr/local/zeek-"${VER}"/bin/* | grep stripped | cut -f1 -d: | xargs strip -s
